### ISSUE TITLE
Make subject categories more intuitive

### ISSUE THREAD

**Issue by ChristopherWong274** [tutorbookapp/tutorbook#46]
no need to repeat math grade1 math grade 2 etc each timeIt will be way easier if when the students select his grade, the system show hi all the subjects which are available. like no need to show him all the subjects from grade1 to 8.

**Comment by nicholaschiang** [comment]
Clarifying what @ChristopherWong274 was saying:
1. The user would select their grade level. For example, "1st Grade".
2. The subject select would then show "Math" instead of "1st Grade Math" because the "1st Grade" would be implied by the user's selected grade.
3. All other subjects would stay the same (e.g. "2nd Grade Math" would still exist).

One concern there is that we'd be confusing the user because they wouldn't know if "Math" was actually "1st Grade Math" or if it was just an over-arching subject area (i.e. if I see "2nd Grade Math" I'm going to be looking for "1st Grade Math" not just "Math").

I'm going to loop the design team in on this too.

**Comment by nicholaschiang** [comment]
@kryssym what do you think about this?

**Comment by ChristopherWong274** [comment]
Yes, that is exactly what I mean

**Comment by kryssym** [comment]
I've been looking at Khan Academy and they have it listed as 

Math by Grade
• 1st Grade
• 2nd Grade
etc

What do you guys think about that?

**Comment by nicholaschiang** [comment]
So earlier (before I updated all the subject options) we were using what Khan Academy was using (i.e. "1st Grade Math", "2nd Grade Math", and so on).

But, until we update the `SubjectSelect` to make it easier on tutors to select those large swaths of subjects (i.e. right now you'd have to individually select all of them), I think we should stick to more broad categories. Most of our tutors will be able to tutor all of those elementary and middle school math subjects anyways.

So for now, I've condensed all of the subjects down into high-level categories that are listed in [this Google Sheet](https://docs.google.com/spreadsheets/u/0/d/18yK2NiODyDTmUOmP3PM8UO7OIKigKv8iL8N-oVQEbhg) (the original subjects are still there with the `[Deprecated]` sheet-name prefix).

@kryssym and @ChristopherWong274 what do you think about this? Does my reasoning make sense?

**Comment by nicholaschiang** [comment]
Ok, I just got rid of all the grade-level subject specifications (i.e. we now only have the "Math" categories instead of "Math Grade 1" and "Math Grade 2"). I think we'll leave it that way for the time being, so I'm closing this issue.
